name: Auto Update Index

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pillow

      - name: Generate index.json
        run: python generate_index.py

      - name: Commit and push index.json + thumbnails
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.json thumbnails/*.png
          git commit -m "🔄 Auto-update index.json and thumbnails" || echo "No changes to commit"
          git push
